[2023-05-01T08:30:25.003+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest-data_dag.spark_ingest_submit_task manual__2023-05-01T08:21:37.814057+00:00 [queued]>
[2023-05-01T08:30:25.044+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest-data_dag.spark_ingest_submit_task manual__2023-05-01T08:21:37.814057+00:00 [queued]>
[2023-05-01T08:30:25.046+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 2
[2023-05-01T08:30:25.098+0000] {taskinstance.py:1350} INFO - Executing <Task(SparkSubmitOperator): spark_ingest_submit_task> on 2023-05-01 08:21:37.814057+00:00
[2023-05-01T08:30:25.111+0000] {standard_task_runner.py:57} INFO - Started process 651 to run task
[2023-05-01T08:30:25.148+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest-data_dag', 'spark_ingest_submit_task', 'manual__2023-05-01T08:21:37.814057+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/ingest_dag.py', '--cfg-path', '/tmp/tmpbmxlr2za']
[2023-05-01T08:30:25.162+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask spark_ingest_submit_task
[2023-05-01T08:30:25.255+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:188: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-05-01T08:30:25.472+0000] {task_command.py:410} INFO - Running <TaskInstance: ingest-data_dag.spark_ingest_submit_task manual__2023-05-01T08:21:37.814057+00:00 [running]> on host 1b6fdd6b3c50
[2023-05-01T08:30:25.733+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='dayookubanjo@yahoo.com' AIRFLOW_CTX_DAG_OWNER='dayookubanjo' AIRFLOW_CTX_DAG_ID='ingest-data_dag' AIRFLOW_CTX_TASK_ID='spark_ingest_submit_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-01T08:21:37.814057+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-01T08:21:37.814057+00:00'
[2023-05-01T08:30:25.767+0000] {spark_submit.py:217} INFO - Could not load connection string spark_local, defaulting to yarn
[2023-05-01T08:30:25.772+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark /opt/***/dags/ingest_data.py
[2023-05-01T08:30:27.762+0000] {spark_submit.py:490} INFO - /home/***/.local/lib/python3.8/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-05-01T08:30:47.265+0000] {spark_submit.py:490} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2023-05-01T08:30:47.274+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2023-05-01T08:30:47.276+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2023-05-01T08:30:47.277+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2023-05-01T08:30:47.278+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2023-05-01T08:30:47.282+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1094)
[2023-05-01T08:30:47.283+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1094)
[2023-05-01T08:30:47.284+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2023-05-01T08:30:47.285+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1111)
[2023-05-01T08:30:47.288+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1120)
[2023-05-01T08:30:47.298+0000] {spark_submit.py:490} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2023-05-01T08:30:47.818+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 421, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark /opt/***/dags/ingest_data.py. Error code is: 1.
[2023-05-01T08:30:47.856+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=ingest-data_dag, task_id=spark_ingest_submit_task, execution_date=20230501T082137, start_date=20230501T083025, end_date=20230501T083047
[2023-05-01T08:30:47.917+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 16 for task spark_ingest_submit_task (Cannot execute: spark-submit --master yarn --name arrow-spark /opt/***/dags/ingest_data.py. Error code is: 1.; 651)
[2023-05-01T08:30:47.965+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-01T08:30:48.155+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
